name: Shot-Perseverance CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install numpy first to anchor the version for mediapipe
        pip install "numpy>=1.23.5,<2.0.0"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest run_test.py
